version: '3.1'

services:
  db:
    image: postgres:9.6.2
    restart: always
    environment:
      POSTGRES_USER: ryougishiki
      POSTGRES_PASSWORD: liaotingwei
      POSTGRES_DB: vividatabase
    ports:
      - 5432:5432