version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - /path/to/your/postgres/data/volume:/var/lib/postgresql/data

  spring-app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - postgres